### ISSUE TITLE
`datadotparl/all-lords.xml` absent from `rawdata`

### ISSUE THREAD

**Issue by samtazzyman** [mysociety/parlparse#100]
I'm trying to run `./crawl-members` from `scripts/datadotparl` as per the README and it's failing with the error
```
Traceback (most recent call last):
  File "./crawl-members", line 44, in <module>
    write(parl_members_url, members_fn)
  File "./crawl-members", line 31, in write
    open(fn, 'w').write(data)
IOError: [Errno 2] No such file or directory: '/parlparse/scripts/datadotparl/../../rawdata/datadotparl/all-lords.xml'
```

**Comment by r4vi** [comment]
@samtazzyman I think you need to run https://github.com/mysociety/parlparse/blob/9f69da4a53aba203c44b325a041c7f90a16aacc7/scripts/datadotparl/update-members first

**Comment by dracos** [comment]
You need to create the output directory, it does not do it for you. In your case, from the above, that is `parlparse/rawdata/datadotparl`

**Comment by dracos** [comment]
PS The readme only really talks about that script, which is one, mostly not relevant, part of this repository's purpose; I don't think it's something other people really need to run, for example. If you're aware of that, that's fine, otherwise http://parser.theyworkforyou.com/ might be more useful (might not).
