### ISSUE TITLE
Party affiliations for years before 1997

### ISSUE THREAD

**Issue by macleginn** [mysociety/parlparse#162]
The membership data in the `people.json` file doesn't seem to have party affiliations for years before 1997. Is this information accessible somewhere else?

**Comment by dracos** [comment]
Yes, Hansard did not contain parties before then, and that's where we sourced our historical information. Since then, the official parliament API at https://data.parliament.uk/membersdataplatform/memberquery.aspx does hold this information, so I guess someone could try and update ours from that, but I imagine that might prove tricky; it's available there anyway.

**Comment by macleginn** [comment]
Thanks! Do you know if the ids in this API correspond to any of the ids in the data or I should match by name?

**Comment by dracos** [comment]
If we've matched already, there's a `datadotparl_id` identifier in our data. Otherwise we use the historic Hansard person ID, but I'm not sure that is actually exposed anywhere else, so isn't that helpful I'm afraid. Some have Wikidata identifiers also. Matching by name will prove quite tricky, for example there were two Rowland Blennerhassets, both MP for Kerry, at the same time: https://en.wikipedia.org/wiki/Kerry_(UK_Parliament_constituency)#Members_of_Parliament

**Comment by macleginn** [comment]
Oh dear. Thanks again!
