### ISSUE TITLE
Parse error in debate

### ISSUE THREAD

**Issue by premasagar** [mysociety/parlparse#42]
A parse error is raised from a recent debate.
Command:
`./lazyrunall.py --date=2016-01-11 scrape parse debates`

reporting:
```
'tag </b> tag out of place in :</b> To ask the Secretary of State if he will make a statement on safety in prisons and secure training centres.'
<< StampURL date:2016-01-11 col:573 aname:160111-0001.htm_spnew121 >>
```

**Comment by dracos** [comment]
The parser has a manual patching interface so that this sort of thing can be fixed by us quickly, for things that are generally not common enough to try and deal with touching the can-be-quite-fragile parser. Whilst the HTML is much better than in the past, it still appears to include manual interventions that can not automatically be fixed, or the time to do so is not worth it. The patches we create are currently available under `patches` at http://www.theyworkforyou.com/pwdata and for this particular day it was http://www.theyworkforyou.com/pwdata/patches/debates/debates2016-01-11a.html.patch which boils down to:

```diff
- <b><b>Andy Slaughter</b> (Hammersmith) (Lab)<i> (Urgent Question)</i>:</b>
+ <b>Andy Slaughter (Hammersmith) (Lab)<i> (Urgent Question)</i>:</b>
```

It looks like we do have some code to try and deal with double bolding: https://github.com/mysociety/parlparse/blob/428a5a318381ebccb70b9eb3c7fd4ad968691a09/pyscraper/runfilters.py#L186-L187 - which didn't work due to the Urgent Question bit being in italics. That regex could probably be tweaked to spot this particular issue, patches welcome, but it's generally easier to use the manual patching.

**Comment by premasagar** [comment]
I see, so parlparse cannot be left to reliably capture the data; it requires occasional manual intervention.
Perhaps sharing the already patched data on TWFY makes sense.

To gather voting data, it looks like the xml files in [/pwdata/scrapedxml/divisionsonly/](http://www.theyworkforyou.com/pwdata/scrapedxml/divisionsonly/) are the most relevant, as they contain the divisions but less data than the files in /debates. Is depending on /divisionsonly supported? The directory isn't mentioned in the [TWFY parser docs](http://parser.theyworkforyou.com), and I can only see a couple of old Perl scripts in the codebase that use it.

**Comment by dracos** [comment]
www.publicwhip.org.uk uses the divisionsonly data, so it should continue to be generated along with everything else. I'm not sure whether it will have enough information (e.g. the auto-detected motion text is frequently wrong and is manually corrected on PublicWhip).

data.parliament.uk includes an API of voting data, for Lords at http://www.data.parliament.uk/dataset/05 (up to date) and for Commons at http://www.data.parliament.uk/dataset/09 (not up to date, not sure why not!).

**Comment by premasagar** [comment]
OK, thanks. Perhaps I better use /debates then, and scan for `<division>` elements.

Yes, I would love to use data.parliament.uk directly, if it had up-to-date data.
