### ISSUE TITLE
Recent votes not on PublicWhip

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/parlparse#92]
There have been votes in the House of Commons since 6 September 2017 but none of them have yet, as of 19 September 2017, appeared on PublicWhip

http://www.publicwhip.org.uk/divisions.php

**Comment by RichardTaylor** [comment]
I've tweeted Richard Bairwell in case it's a PublicWhip issue 

https://twitter.com/RTaylorUK/status/910166471178899456

**Comment by rbairwell** [comment]
Looks like it's a PW issue relating to loading in the "redirect" entries within members/people.json (PW doesn't cope with this at the moment) . Seeing how this can be patched.

**Comment by rbairwell** [comment]
Fixed.

**Comment by RichardTaylor** [comment]
Closing. Might be worth letting @rbairwell know about any ParlParse changes which are expected to impact PublicWhip?

**Comment by dracos** [comment]
Redirects have existed in people.json since May 2015; I believed I had updated the PW code to cope (and indeed hadn't had any issues until this one), so perhaps the underlying issue is something else. Perhaps something is referring to a redirecting person ID rather than the redirected, which shouldn't happen, not sure.
